export const makeupPlans = [
  {
    name: "Starter",
    price: "INR 5,999",
    billing: "One-time website development cost",
    note: "Domain and hosting charged yearly.",
    description: "For freelance makeup artists starting their online presence.",
    features: [
      "Website ready in 7 days",
      "Personal artist profile website",
      "Basic portfolio gallery for makeup looks",
      "Services and pricing showcase",
      "Direct WhatsApp inquiry button",
      "Mobile optimized design",
      "Basic Google visibility setup",
    ],
    cta: "Start My Website",
  },
  {
    name: "Pro",
    price: "INR 9,999",
    billing: "One-time website development cost",
    note: "Domain and hosting charged yearly.",
    description: "For bridal and event artists who want more bookings.",
    highlight: "Most Popular",
    badgeNote: "Best value for working artists",
    features: [
      "Website ready in 10 days",
      "Everything in Starter",
      "Advanced portfolio galleries",
      "Testimonials and client reviews",
      "Smart lead capture form",
      "Google Business profile optimization",
      "Instagram and WhatsApp booking integration",
    ],
    cta: "Get My Website",
  },
  {
    name: "Premium",
    price: "INR 14,999",
    billing: "One-time website development cost",
    note: "Domain and hosting charged yearly.",
    description: "For premium artists building a strong brand presence.",
    features: [
      "Website ready in 14 days",
      "Everything in Pro",
      "Premium service package presentation",
      "Bridal campaign landing pages",
      "Priority design updates",
      "Advanced SEO for local bookings",
    ],
    cta: "Launch My Website",
  },
  {
    name: "Elite",
    price: "INR 19,999",
    billing: "One-time website development cost",
    note: "Domain and hosting charged yearly.",
    description: "For studios and teams scaling their makeup business.",
    features: [
      "Dedicated launch manager",
      "Everything in Premium",
      "Multi artist or team website structure",
      "Appointment workflow consultation",
      "Ongoing booking improvement ideas",
      "Priority WhatsApp support",
    ],
    cta: "Start My Website",
  },
];

export const whyChooseBenefits = [
  "Get discovered on Google",
  "Turn Instagram visitors into bookings",
  "Professional website without technical hassle",
];
